/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DoctorDAL;
import Entidades.Doctor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUAN CARLOS
 */
public class frmListaDoctores extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListaDoctores
     */
    DefaultTableModel modelo=new DefaultTableModel();
    String columna[]={"CODIGO","NOMBRES Y APELLIDOS","USUARIO","ESPECIALIDAD","ESTADO"};
    public frmListaDoctores() {
        initComponents();
        modelo.setDataVector(devolverdatos(), columna);
    }
    private Object[][] devolverdatos()
    {
        
        ResultSet rs=DoctorDAL.getInstance().mostrarDoctor();
        int n=DoctorDAL.getInstance().cantidadDoctores();
        labresultado.setText(String.valueOf(n));
        Object[][] datos=null;
        try {
            datos=new Object[n][5];
            int i=0;
            while(rs.next())
            {
                datos[i][0]=rs.getInt(1);
                datos[i][1]=rs.getString(2)+" "+rs.getString(3);
                datos[i][2]=rs.getString(4);
                datos[i][3]=rs.getString(6);
                datos[i][4]=rs.getString(5);
                i++;
            }
        } catch (Exception ex) {
            
        }
        return datos;
    }
    private Object[][] devolverdatos2(ResultSet rs,int n)
    {
        
        
        labresultado.setText(String.valueOf(n));
        Object[][] datos=null;
        try {
            datos=new Object[n][5];
            int i=0;
            while(rs.next())
            {
                datos[i][0]=rs.getInt(1);
                datos[i][1]=rs.getString(2)+" "+rs.getString(3);
                datos[i][2]=rs.getString(4);
                datos[i][3]=rs.getString(6);
                datos[i][4]=rs.getString(5);
                i++;
            }
        } catch (Exception ex) {
            
        }
        return datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labresultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        setTitle("LISTA DE DOCTORES");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Relacion de Doctores");

        labresultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labresultado.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Resultado:");

        tabla.setModel(modelo);
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla.setFillsViewportHeight(true);
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        tabla.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tabla.getTableHeader().setResizingAllowed(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/docto.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(btnnuevo)
                .addGap(18, 18, 18)
                .addComponent(btneditar)
                .addGap(27, 27, 27)
                .addComponent(btneliminar)
                .addGap(29, 29, 29)
                .addComponent(btnbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(labresultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnnuevo)
                    .addComponent(btneditar)
                    .addComponent(btneliminar)
                    .addComponent(btnbuscar)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(labresultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        NewDoctor newDoctor=new NewDoctor(null, true);
        newDoctor.setVisible(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        int row=tabla.getSelectedRow();
        if(row>-1)
        {
            int idcodigo=Integer.parseInt(tabla.getValueAt(row, 0).toString());
            UpdateDoctor updateDoctor=new UpdateDoctor(null, true, idcodigo);
            updateDoctor.setVisible(true);
            
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Mensaje", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {
            // TODO add your handling code here:
            String usuario=JOptionPane.showInputDialog("Ingrese Usuario");
            ResultSet rs=DoctorDAL.getInstance().buscarDoctorUsuario(usuario);
            if(rs.getRow()>0){
                modelo.setDataVector(devolverdatos2(rs,rs.getRow()), columna);
            }
            else
                JOptionPane.showMessageDialog(null, "Datos No encontrados", "Mensaje", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(frmListaDoctores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        int row=tabla.getSelectedRow();
        if(row>-1)
        {
            int idcodigo=Integer.parseInt(tabla.getValueAt(row, 0).toString());
            if(DoctorDAL.getInstance().eliminarDoctor(idcodigo,"I")>0)
                JOptionPane.showMessageDialog(null, "Doctor Eliminado");
            else
                JOptionPane.showMessageDialog(null, "Error de eliminacion", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Mensaje", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btneliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labresultado;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
