/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.PacienteDAL;
import Entidades.Doctor;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import static Presentacion.Principal.doctor;
import javax.swing.JOptionPane;

/**
 *
 * @author JUAN CARLOS
 */
public class frmListaPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListaPacientes
     */
    DefaultTableModel modelo=new DefaultTableModel();
    String columna[]={"CODIGO","REGISTRO","NOMBRES Y APELLIDOS","FECHA NAC","DIRECCION","TELEFONO","EMAIL","OCUPACION","ESTADO"};
    public frmListaPacientes() {
        initComponents();
        modelo.setDataVector(devolverdatos(), columna);
    }
    private Object[][] devolverdatos()
    {
        
        ResultSet rs=PacienteDAL.getInstance().mostrarPacientes();
        int n=PacienteDAL.getInstance().cantidadPacientes();
        labresultado.setText(String.valueOf(n));
        Object[][] datos=null;
        try {
            datos=new Object[n][9];
            int i=0;
            while(rs.next())
            {
                datos[i][0]=rs.getInt(1);
                datos[i][1]=rs.getDate(10);
                datos[i][2]=rs.getString(2)+" "+rs.getString(3);
                datos[i][3]=rs.getDate(5);
                datos[i][4]=rs.getString(7);
                datos[i][5]=rs.getString(8);
                datos[i][6]=rs.getString(9);
                datos[i][7]=rs.getString(4);
                datos[i][8]=rs.getString(14);
                i++;
            }
        } catch (Exception ex) {
            
        }
        return datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labresultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        setTitle("LISTA DE PACIENTES");

        tabla.setModel(modelo);
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla.setFillsViewportHeight(true);
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        tabla.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tabla.getTableHeader().setResizingAllowed(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Relacion de Pacientes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Resultado:");

        labresultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labresultado.setText("jLabel3");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/docto.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btnnuevo)
                .addGap(36, 36, 36)
                .addComponent(btneditar)
                .addGap(31, 31, 31)
                .addComponent(btneliminar)
                .addGap(124, 124, 124)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(labresultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnnuevo)
                        .addComponent(btneditar)
                        .addComponent(btneliminar)
                        .addComponent(jLabel2)
                        .addComponent(labresultado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        NewPaciente newPaciente=new NewPaciente(null, true,doctor);
        newPaciente.setVisible(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        int row=tabla.getSelectedRow();
        if(row>-1)
        {
            int idcodigo=Integer.parseInt(tabla.getValueAt(row, 0).toString());
            UpdatePaciente updatePaciente=new UpdatePaciente(null, true, idcodigo);
            updatePaciente.setVisible(true);
            
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Mensaje", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        int row=tabla.getSelectedRow();
        if(row>-1)
        {
            int idcodigo=Integer.parseInt(tabla.getValueAt(row, 0).toString());
            if(PacienteDAL.getInstance().eliminarPaciente(idcodigo,"I")>0)
                JOptionPane.showMessageDialog(null, "Paciente Eliminado");
            else
                JOptionPane.showMessageDialog(null, "Error de eliminacion", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Mensaje", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btneliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labresultado;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
