/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelFondo.java
 *
 * Created on 21/09/2010, 04:43:20 PM
 */

package Presentacion;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.*;

/**
 *
 * @author juan contreras
 */
public class JPanelFondo extends javax.swing.JPanel {

    /** Creates new form JPanelFondo */
    JFrame F;
    JPanel R;
    int x;
    public JPanelFondo(JFrame f,int t) {
        initComponents();
        x=t;
        F=f;
        Dimension d=F.getSize();//dimencion del JFrame
        this.setSize(d.width,d.height);//ingresando el ancho y altura del JFrame actual
    }
    @Override
    public void paintComponent(Graphics g){
        if(x==1){
        Dimension tamanio = F.getSize();//tamaño del Frame
        setSize(tamanio.width,tamanio.height);//ingresando el ancho y altura el tamaño
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/imagenes/Fondo1.png"));
        // en ImageIcon obtenemos la imagen del paquete Imagen
        g.drawImage(imagenFondo.getImage(), 0, 0,tamanio.width, tamanio.height, null);
        setOpaque(false);
        super.paintComponent(g);
        }else
            if(x==2){
                Dimension tamanio = F.getSize();//tamaño del Frame
                setSize(tamanio.width,tamanio.height);//ingresando el ancho y altura el tamaño
                ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/capaImagen/pared.jpg"));
                // en ImageIcon obtenemos la imagen del paquete Imagen
                g.drawImage(imagenFondo.getImage(), 0, 0,tamanio.width, tamanio.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
            else
                if(x==3){
                    Dimension tamanio = F.getSize();//tamaño del Frame
                    setSize(tamanio.width,tamanio.height);//ingresando el ancho y altura el tamaño
                    ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/capaImagen/fondoSO.JPG"));
                    // en ImageIcon obtenemos la imagen del paquete Imagen
                    g.drawImage(imagenFondo.getImage(), 0, 0,tamanio.width, tamanio.height, null);
                    setOpaque(false);
                    super.paintComponent(g);
                }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
